title = "Log4Net"

syntax = [
	"Begin",
	{ Skip = 23 },
	{ EmitDate = { name = "Date", width = 21 } },
	{ Skip = 2 },
	"Begin",
	{ SkipUntilChar = " " },
	{ EmitEnumeration = { name = "Level", width = 5, enumerations = ["TRACE", "DEBUG", "INFO", "WARN", "ERROR", "FATAL"] } },
	{ SkipUntilChar = "[" },
	{ Skip = 1 },
	"Begin",
	{ SkipUntilChar = "]" },
	{ EmitString = { name = "Context", width = 5 } },
	{ SkipUntilChar = "[" },
	{ Skip = 1 },
	"Begin",
	{ SkipUntilChar = "]" },
	{ EmitString = { name = "Thread", width = 5 } },
	{ Skip = 2 },
	"Begin",
	{ SkipUntilChar = "," },
	{ EmitString = { name = "File", width = 30 } },
	{ Skip = 3 },
	"Begin",
	{ SkipUntilString = " <" },
	{ EmitString = { name = "Method", width = 15 } },
	{ Skip = 2 },
	"Begin",
	{ SkipUntilChar = ">" },
	{ EmitString = { name = "Object", width = 4 } },
	{ SkipUntilChar = "-" },
	{ Skip = 2 },
	"Begin",
	{ EmitRemainder = { name = "Message", width = -1 } }
]
