WHITESPACE = _{ " " | "\t" | "\r" | "\n" }
OPERATOR = { OR | AND }
	OR = { "|" }
    AND = { "&" }
STRING = @{ CHAR+ ~ (WHITESPACE ~ CHAR+)* }
BANNED_CHAR = _{ OPERATOR | PARENTHESES | "\\" }
ESCAPED_CHAR = { "\\" ~ BANNED_CHAR }
CHAR = { (!(BANNED_CHAR | WHITESPACE) | ESCAPED_CHAR) ~ (ESCAPED_CHAR | ANY) }
PARENTHESES = { "(" | ")" }

ATOM = _{ STRING | "(" ~ EXPR ~ ")" }
EXPR = { ATOM ~ (OPERATOR ~ ATOM)* }
QUERY = _{ SOI ~ EXPR ~ EOI }
