string = ${ "\"" ~ inner ~ "\"" }
inner = @{ char* }
char = {
    !("\"" | "\\") ~ ANY
    | "\\" ~ ("\"" | "\\" | "/" | "b" | "f" | "n" | "r" | "t")
    | "\\" ~ ("u" ~ ASCII_HEX_DIGIT{4})
}

operation = _{ and | or }
    and = { "&&" }
    or = { "||" }

not = { "!" }

column_name = { ASCII_ALPHANUMERIC+ }

filter = { column_name ~ "=" ~ expr }

expr = { term ~ (operation ~ term)* }
term = _{ not{0,1} ~ (string | "(" ~ expr ~ ")") }

WHITESPACE = _{ " " | "\t" }
